# Generated by Django 5.2 on 2025-04-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email of the person submitting the questionnaire', max_length=254)),
                ('submission_date', models.DateTimeField(auto_now_add=True, help_text='Date and time of submission')),
                ('data', models.JSONField(help_text='The questionnaire data in JSON format')),
            ],
            options={
                'verbose_name': 'Questionnaire Submission',
                'verbose_name_plural': 'Questionnaire Submissions',
                'ordering': ['-submission_date'],
            },
        ),
    ]
