# Generated by Django 5.2 on 2025-04-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairesubmission',
            name='file',
            field=models.FileField(blank=True, help_text='The original Excel questionnaire file', null=True, upload_to='questionnaires/'),
        ),
    ]
